include $(TOP_DIR)/Makefile.env

SRCS := $(wildcard *.c)
#OBJS := $(patsubst %.c, %.o,$(SRCS))
#echo "\trm -f *.d" >> $@;
#mv $@ $(TOP_DIR)/$(OBJ_DEP);
OBJS := $(TOP_DIR)/$(OBJ_DIR)/$(patsubst %.c, %.o,$(SRCS))

SUB_DIR = $(shell ls -l ../|grep ^d |awk '{print $$9}')

INC_DIR = $(addprefix -I../,$(SUB_DIR))
INCS = $(foreach dir, $(INC_DIR), $(dir))

INCS += -I../../include

all: $(OBJS)

CMD := $(CC) -c $< $(CFLAGS) $(INCS)

%.d:%.c 
	@rm -f *.d;\
	$(CC) -MM $(INCS) $< > $@;\
	echo "\t"$(CMD)" "$< >> $@;\
	echo "\t@mv $(patsubst %.d, %.o,$@) $(TOP_DIR)/$(OBJ_DIR);\\" >> $@;\
	echo "\trm -f *.d" >> $@;

include $(SRCS:.c=.d)	

.PHONY: all
