include $(TOP_DIR)/Makefile.env

SRCS := $(wildcard *.c)
OBJS := $(patsubst %.c,%.o,$(SRCS))
DEPS := $(patsubst %.c,%.d,$(SRCS))
SUB_DIR = $(shell ls -l ../|grep ^d |awk '{print $$9}')

INC_DIR = $(addprefix -I../,$(SUB_DIR))
INCS = $(foreach dir, $(INC_DIR), $(dir))
INCS += -I../../include

CMD := $(CC) -c $< $(CFLAGS) $(INCS)

all: $(DEPS)

%.d : %.c
	@set -e; rm -f $@; $(CC) -MM $< $(INCS) > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,$(TOP_DIR)/$(OBJ_DIR)/\1.o :,g' < $@.$$$$ > $@; \
	echo "\t"$(CMD)" "$< >> $@; \
	echo "\t@mv $(patsubst %.d, %.o,$@) $(TOP_DIR)/$(OBJ_DIR);\\" >> $@; \
	$(MAKE) -f $@; \
	rm -f $@ $@.$$$$
